title: Savi
description: >-
  A fast language for programmers who are passionate about their craft.
baseurl: "" # the subpath of the site (currently none)
url: "https://savi-lang.github.io"
twitter_username: savi-lang
github_username: savi-lang

sass:
  style: compact

# The collections subdirectories to look for and build.
collections:
  index:
    output: true
    permalink: /:name
    order:
      - concepts.md
      - tutorial.md
  concepts:
    output: true
    permalink: /:collection/:name
    order:
      - concurrency-safety.md
      - mutability.md
      - aliasing.md
  tutorial:
    output: true
    permalink: /:collection/:name
    order:
      - first-program.md
